#https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace/
---
apiVersion: 1
kind: Namespace
metadata:
  name: quota-pod
  labels:
    name: quota-pod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-demo
  namespace: quota-pod
spec:
  hard:
    pods: "2"
---
apiVersion: apps/v1
kind: Deployment
#inicio informacion deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "cambio de puerto"
  namespace: quota-pod
  name: deployment-qa
  labels:
    app: front
#fin informacion deployment
#inicio informacion replicaset
spec:
#  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
#fin informacion replicaset
#Inicio infoacion pods
    spec:
      containers:
      - name: nginx
        image: nginx:nada
        ports:
        - containerPort: 80