apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-pvc #nombre a mencionar en los pods
spec:
  storageClassName: standard #se puede eliminar esta línea.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi