#https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx:alpine
    name: test
    volumeMounts:
    - mountPath: /var/log/nginx
      name: vol
  volumes:
  - name: vol
    emptyDir: {}
