apiVersion: v1
kind: Pod
metadata:
 name: doscont
spec:
 containers:
 - name: con1
   image: python:3.6-alpine
   command: ['sh','-c','echo contenedor1 > index.html && python -m http.server 8082']
 - name: con2
   image: python:3.6-alpine
   command: ['sh','-c','echo contenedor2 > index.html && python -m http.server 8083']
