apiVersion: v1
kind: Pod
metadata:
 name: podtest2
 labels:
   app: front
   env: dev
spec:
 containers:
 - name: con1
   image: nginx:alpine
   command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
---
apiVersion: v1
kind: Pod
metadata:
 name: podtest3
 labels:
   app: back
   env: prod
spec:
 containers:
 - name: con1
   image: nginx:alpine
   command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
---
apiVersion: v1
kind: Pod
metadata:
 name: podtest4
 labels:
   app: back
   env: prod
spec:
 containers:
 - name: con1
   image: nginx:alpine
   command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
