apiVersion: apps/v1
kind: Deployment
#inicio informacion deployment
metadata:
  annotations:
  name: backend-k8s-practica
  labels:
    app: backend
#fin informacion deployment
#inicio informacion replicaset
spec:
#  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
#fin informacion replicaset
#Inicio infoacion pods
    spec:
      containers:
      - name: backend
        image: k8s-practica:v2
        imagePullPolicy: IfNotPresent
---
## Creacion del servicio
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-practica
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
