apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  username: usuario
  password: "mypass"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    volumeMounts:
    - name: test
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: mysecret
      items:
      - key: username
        path: user.txt