apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-test
  labels:
    app: rs-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-label
  template:
   metadata:
     labels:
      app: pod-label
   spec:
     containers:
     - name: con1
       image: python:3.6-alpine
       command: ['sh','-c','echo contenedor1 > index.html && python -m http.server 8082']
     - name: con2
       image: python:3.6-alpine
       command: ['sh','-c','echo contenedor2 > index.html && python -m http.server 8083']
